#!/usr/bin/env python3
"""Render starter tables from templates/starters.json; --check rejects doc drift."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ('README.md', 'docs/GAME_QUICKSTART.md', 'docs/PORTABLE_GAMES.md')
BEGIN, END = '<!-- starters:begin -->', '<!-- starters:end -->'


def render(root=ROOT, document='README.md'):
    data = json.loads((root / 'templates/starters.json').read_text(encoding='utf-8'))
    rows = [BEGIN, '<!-- Generated by tools/starter_docs.py; edit templates/starters.json. -->',
            '| Starter | Rules and use | Collision | Networking |', '|---|---|---|---|']
    for name, spec in data['starters'].items():
        default = ' (CLI default)' if name == data['cli_default'] else ''
        guide = Path(spec['guide']).relative_to('docs').as_posix() if document.startswith('docs/') else spec['guide']
        rows.append(f"| [`{name}`]({guide}){default} | {spec['use']} | {spec['collision']} | {', '.join(spec['networking'])} |")
    return '\n'.join([*rows, END])


def update(root=ROOT, check=False):
    stale = []
    for name in DOCS:
        path = root / name
        text = path.read_text(encoding='utf-8')
        start, end = text.index(BEGIN), text.index(END) + len(END)
        expected = text[:start] + render(root, name) + text[end:]
        if expected != text:
            stale.append(name)
            if not check:
                path.write_text(expected, encoding='utf-8')
    return stale


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    stale = update(check=args.check)
    if args.check and stale:
        parser.exit(1, 'Starter table drift: ' + ', '.join(stale) + '; run tools/starter_docs.py\n')
